config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues do
    collection do
      get :personal_index
    end
    resources :bookings, only: [:index, :new, :create, :show, :edit, :update]
  end
  resources :users, only: [] do
    get 'bookings', to: "bookings#personal_index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :venue
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :venues, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  VENUE_TYPE = ['Wedding', 'Birthday', 'Business']
  DEFAULT_PHOTO = "https://source.unsplash.com/random/500x150"

  validates :category, inclusion: { in: VENUE_TYPE }
  validates :name, presence: true
  validates :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.categories
    VENUE_TYPE
  end

  def photo_or_default
    photo.file.nil? ? DEFAULT_PHOTO : photo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_venue, except: [:personal_index]

  def index
    @bookings = @venue.bookings.where(user: current_user)
  end

  def personal_index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = @venue.bookings.find(params[:id])
  end

  def new
    @booking = @venue.bookings.new
  end

  def create
    @booking = @venue.bookings.new(booking_params)
    @booking.user = current_user
    @booking.price = (@booking.final_date - @booking.initial_date) * @venue.price
    if @booking.save
      redirect_to venue_booking_path(@venue, @booking)
    else
      render :new
    end
  end

  def edit
    @booking = @venue.bookings.find(params[:id])
  end

  def update
    @booking = @venue.bookings.find(params[:id])
    @booking.update(booking_params)
    redirect_to venue_booking_path(@venue, @booking)
  end

  private

  def set_venue
    @venue = Venue.find(params[:venue_id])
  end

  def booking_params
    params.require(:booking).permit(:initial_date, :final_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @venue_types = []
    @venue_types << "All"
    @venue_types += Venue::VENUE_TYPE
    @venues = Venue.all
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!
  def index
    @venues = Venue.near(params[:query], 100)
    @markers = @venues.map do |venue|
      {
        lng: venue.longitude,
        lat: venue.latitude,
        infoWindow: { content: render_to_string(partial: "/venues/map_box", locals: { venue: venue }) }
      }
    end
  end

  def personal_index
    @venues = Venue.where(user: current_user)
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to root_path
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address, :category, :price, :photo)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [venue, booking] do |f| %>
  <div class="form-inline">
    <%= f.input :initial_date, as: :date, html5: true %>
    <%= f.input :final_date, as: :date, html5: true %>
  </div>
  <br>
  <%= f.button :button, "Create", class: "btn-primary search-box__button" %>
<% end %>

app/views/bookings/edit.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Edit your booking </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
      <div class="search-box">
        <%= render 'bookings/form', venue: @venue, booking: @booking %>
      </div>


    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Find here all your venue's bookings </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">

<% @bookings.each do |b| %>
  <p><%= b.initial_date %></p>
  <p><%= b.final_date %></p>
  <p><%= b.user.email %></p>
  <p><%= b.price %></p>
  <% end %>

<div class="quick-button">Edit</div>
<div class="quick-button">Delete</div>
</div>

</div>

app/views/bookings/new.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Book this venue </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>

<div class="container">
  <div class="row">
      <div class="search-box">
        <%= render 'bookings/form', venue: @venue, booking: @booking %>
      </div>


		</div>
	</div>
</div>
</div>

</div>
</div>

app/views/bookings/personal_index.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
<br>
<br>
  <h2 class="fontsmallbanner"> Your bookings </h2>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <% @bookings.each do |b| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card">
          <img class="card-img-top img-responsive" src="https://source.unsplash.com/random/2500x1500" alt="wedding">
          <div class="card-category"> <%= b.venue.category %> </div>
          <div class="card-name"><%= b.venue.name %></div>
          <div class="card-address">  <%= b.user.email %></div>
          <div class="card-price"><%= b.final_date %></div>
          <button class="quick-button">Edit</button>
        </div>

      </div>
    <% end %>

</div>
</div>

</div>
</div>

app/views/bookings/show.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Bookings of <%= @booking.venue.name %>  </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>

<p><%= @booking.initial_date %></p>
<p><%= @booking.final_date %></p>
<p><%= @booking.user.email %></p>
<p><%= @booking.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
<!--     <style> body {background: linear-gradient(to left, #654ea3, #eaafc8);}</style>
 -->  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.14.0"></script>
    <%= javascript_pack_tag 'searchbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1469371670807-013ccf25f16a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=fda822492d9c9c4d365f2ca1e9e02ada&auto=format&fit=crop&w=1050&q=80');">
  <div class="banner-content">
    <div class="banner-wrap">
     <div class="search">
      <h1>So, where's the party?</h1>
      <%= render 'shared/searchbar' %>
    </div>
  </div>
</div>
</div>


<div class="custom-container container">
  <div class="custom-row row">
<br>
    <h2> Browse all our venues here! </h2>
<br>
    <% @venues.each do |venue| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= render 'venues/card', venue: venue %>
      </div>
    <% end %>
</div>
</div>

<footer class="footer">
  <h1 class="text">THE AIRBNB OF VENUES</h1>
  <h2 class="text2">&copy;MADE IN RIO</h2>
  <h2 class="text3">-POWERED BY THE DOPCAST TEAM-</h2>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</footer>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h1 class="text">THE AIRBNB OF VENUES</h1>
  <h2 class="text2">&copy;MADE IN RIO</h2>
  <h2 class="text3">-POWERED BY THE DOPCAST TEAM-</h2>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png"%>
  <% end %>

  <!-- Search bar -->
<!--   <form class="navbar-form" role="search">
      <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name="q">
          <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
      </div>
  </form>
 -->
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <%= link_to "Your Venues", personal_index_venues_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Your Bookings", user_bookings_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Create a Venue", new_venue_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "https://cdn0.iconfinder.com/data/icons/superuser-web-kit/512/686909-user_people_man_human_head_person-512.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
     <!--      <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li> -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>

    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%=  form_tag(venues_path, method: "get") do %>


  <input type="search" name="query" id="address" class="form-control" placeholder="Where's the party tonight?" />
  <button type="submit" class="searchButton">
    <i class="fa fa-search"></i>
  </button>
<% end %>

app/views/venues/_card.html.erb
<div class="card">
  <div class="card-photo"> <%= cl_image_tag venue.photo_or_default %> </div>
  <div class="card-category"> <%= venue.category %> </div>
  <div class="card-name"><%= link_to venue.name, venue_path(venue) %></div>
  <div class="card-address"><%= venue.address %></div>
  <div class="card-price">R$ <%= venue.price %></div>
</div>

app/views/venues/_form.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Here it is </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>
<%= form_for(@venue) do |f| %>

<div class="form-group">
  <%= f.label :category %>
  <%= f.text_field :category, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price, class: 'form-control' %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/venues/_map_box.html.erb
<!-- Contents inside map popup -->

<h3><%= link_to venue.name, venue_path(venue) %></h3>
<p>Address: <%= venue.address %></p>
<p>Price: R$ <%= venue.price %></p>

app/views/venues/edit.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Edit your venue </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= form_for([@user, @venue]) do |f| %>

      <div class="form-group">
        <%= f.label :category %>
        <%= f.text_field :category, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <%= f.submit class: 'createbutton' %>
      <% end %>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="main-container">
<!--   <h2> Search for your perfect venue on the map </h2>
-->  <div class="row">
  <div class="col-xs-6">
    <div class="card-index">
      <% @venues.each do |venue| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= render 'venues/card', venue: venue %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-6">

    <div
    id="map"
    style="width: 100%;
    height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>
</div>

app/views/venues/new.html.erb
<!-- <div class="smallbanner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=af5af77aed859c2f16c5234900f54ab9&auto=format&fit=crop&w=1350&q=80');"> -->
<div id="smallbanner">
<br>
<br>
<br>
<br>
<br>
<br>
  <h2 class="fontsmallbanner"> Party time</h2>
<!--   <p class="fontsmallbanner">Tell us more about your fantastic venue</p>
 --></div>

  <div class="formcontainer">
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
			<h3>Add a venue</h3>

      <%# simple_form_for(@venue) do |f| %>
        <%# f.input :photo %>
        <%# f.input :photo_cache, as: :hidden %>
      <%# end %>

			<%= simple_form_for(@venue) do |f| %>

			<div class="form-group">
				<%= f.label :category %>
				<%= f.text_field :category, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.label :address %>
				<%= f.text_field :address, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.label :price %>
				<%= f.text_field :price, class: 'form-control' %>
			</div>


      <div class="form-group">
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
      </div>


      <%= f.submit class: 'createbutton' %>
			<% end %>
		</div>
	</div>
</div>

app/views/venues/personal_index.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
<br>
<br>
  <h2 class="fontsmallbanner"> Your venues </h2>
  <p class="fontsmallbanner"></p>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
<!--     <h2> Here are listed the venues you created </h2>
 --><br>

    <% @venues.each do |venue| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card">
         <%= render 'venues/card', venue: venue %>
        </div>
      </div>
    <% end %>
</div>
</div>

app/views/venues/show.html.erb
<div id="smallbanner">
<br>
<br>
<br>
<br>
  <h1 class="fontsmallbanner"> Here are this venue's information </h1>
  <p class="fontsmallbanner"></p>
<br>
<br>

<%= render 'venues/card', venue: @venue %>

<% if @venue.user == current_user %>
  <a class="actionbutton" <%= link_to 'Edit this Venue', edit_venue_path(@venue) %> </a>
  <a class="actionbutton" <%= link_to 'View bookings', venue_bookings_path(@venue, @booking) %> </a>
  <a class="actionbutton" <%= link_to 'Delete this Venue', venue_path(@venue), method: :delete, data: { confirm: "Are you sure you want to delete this Venue?" } %>
<% else %>
  <%= link_to 'Book this Venue', new_venue_booking_path(@venue, @booking) %>
<% end %> </a>

<a class="actionbutton" <%= link_to 'Back to Home', root_path %> </a>